name: Deploy Rosenwald Theme via Git Tag

on:
  push:
    tags:
      - 'v*.*.*-*'  # e.g., v1.0.0-dev, v1.2.3-prod

jobs:
  parse-env:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.setenv.outputs.env }}
      tag_name: ${{ github.ref_name }}
    steps:
      - name: Parse environment from tag
        id: setenv
        run: |
          TAG="${{ github.ref_name }}"
          ENV=$(echo "$TAG" | grep -oE '(dev|test|stage|prod)$')
          if [ -z "$ENV" ]; then
            echo "Tag must end in -dev, -test, -stage, or -prod"
            exit 1
          fi
          echo "env=$ENV" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

  deploy:
    needs: parse-env
    runs-on: self-hosted
    environment: ${{ needs.parse-env.outputs.env_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package theme artifact  # Zip the theme for deployment
        run: |
          THEME_NAME="Rosenwald-Fund-Collection"
          TAG="${{ needs.parse-env.outputs.tag_name }}"
          ZIP_NAME="${THEME_NAME}_${TAG}.zip"

          zip -r "$ZIP_NAME" . -x ".git/*"

          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Upload artifact to S3  # Push the zip file to S3
        run: |
          aws s3 cp "$ZIP_NAME" "s3://${{ secrets.S3_BUCKET_NAME }}/${{ needs.parse-env.outputs.env_name }}/artifacts/themes/$ZIP_NAME"

      - name: Trigger and Monitor Remote Deployment via SSM
        id: ssm
        run: |
          ENV="${{ needs.parse-env.outputs.env_name }}"
          TAG="${{ needs.parse-env.outputs.tag_name }}"
          INSTANCE_ID="${{ secrets.INSTANCE_ID }}"
          S3_BUCKET="${{ secrets.S3_BUCKET_NAME }}"
          ZIP_NAME="Rosenwald-Fund-Collection_${TAG}.zip"

          # Start remote command on EC2 via SSM
          CMD_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids "$INSTANCE_ID" \
            --comment "Deploy Theme: $TAG" \
            --parameters "commands=[\"aws s3 cp s3://$S3_BUCKET/$ENV/artifacts/themes/$ZIP_NAME /tmp/theme-artifact.zip\",\"unzip -o /tmp/theme-artifact.zip -d /tmp/deployed-theme\",\"chmod +x /tmp/deployed-theme/.github/workflows/deploy.sh\",\"/tmp/deployed-theme/.github/workflows/deploy.sh $ENV $TAG\"]" \
            --region us-east-1 \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $CMD_ID"
          echo "Waiting for execution to complete..."
          sleep 15

          # Poll until command completes or timeout
          STATUS="InProgress"
          TIMEOUT=60
          ELAPSED=0

          while [[ "$STATUS" == "InProgress" && "$ELAPSED" -lt "$TIMEOUT" ]]; do
            STATUS=$(aws ssm get-command-invocation \
              --command-id "$CMD_ID" \
              --instance-id "$INSTANCE_ID" \
              --region us-east-1 \
              --query "Status" \
              --output text)
            echo "Current status: $STATUS"
            sleep 5
            ELAPSED=$((ELAPSED + 5))
          done

          # If command failed, mark GitHub Actions job as failed
          if [[ "$STATUS" != "Success" ]]; then
            echo "::error ::Deployment failed with status: $STATUS"
          fi

          # Show command output from EC2 in GitHub logs
          echo "==== SSM OUTPUT BEGIN ===="
          aws ssm get-command-invocation \
            --command-id "$CMD_ID" \
            --instance-id "$INSTANCE_ID" \
            --region us-east-1 \
            --query "StandardOutputContent" \
            --output text || echo "[ERROR] Failed to fetch output"
          echo "==== SSM OUTPUT END ===="